### ISSUE TITLE
疑似框架内报错：java.util.List.iterator()' on a null object reference

### ISSUE THREAD

**Issue by techwn** [sunshinejr/RxPermission#22]
这是我在友盟看到的报错：
Caused by: e.b.f: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
	at e.d.d.c$a.a(InternalObservableUtils.java:386)
	at e.d.d.c$a.a(InternalObservableUtils.java:383)
	at e.d.d.a.a(ActionSubscriber.java:44)
	at e.e.b.b(SafeSubscriber.java:157)
	at e.e.b.a(SafeSubscriber.java:120)
	at e.b.b.a(Exceptions.java:204)
	at e.e.b.a(SafeSubscriber.java:144)
	at e.d.a.r$e.a(OperatorMerge.java:505)
	at e.d.a.r$e.b(OperatorMerge.java:463)
	at e.d.a.r$e.a(OperatorMerge.java:246)
	at e.d.a.r$e.a(OperatorMerge.java:147)
	at e.d.a.q$a.a(OperatorMap.java:74)
	at e.d.a.n$a.a(OperatorBufferWithSize.java:114)
	at e.d.a.r$e.a(OperatorMerge.java:393)
	at e.d.a.r$e.a(OperatorMerge.java:355)
	at e.d.a.r$c.a(OperatorMerge.java:840)
	at e.e.c.a(SerializedObserver.java:95)
	at e.e.d.a(SerializedSubscriber.java:95)
	at e.d.a.d$c.b(OnSubscribeConcatMap.java:182)
	at e.d.a.d$b.a(OnSubscribeConcatMap.java:335)
	at e.h.d$b.a(SubjectSubscriptionManager.java:225)
	at e.h.b.a(PublishSubject.java:114)
	at com.tbruyelle.rxpermissions.RxPermissionsFragment.a(RxPermissionsFragment.java:66)
	at com.tbruyelle.rxpermissions.RxPermissionsFragment.onRequestPermissionsResult(RxPermissionsFragment.java:51)
	at android.app.Activity.dispatchRequestPermissionsResultToFragment(Activity.java:6733)
	at android.app.Activity.dispatchActivityResult(Activity.java:6605)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:3733)
	... 9 more

说是：RxPermissionsFragment第66行。具体是这一行：
subject.onNext(new Permission(permissions[i], granted, shouldShowRequestPermissionRationale[i]));

版本是最新的0.9.4。
这是我的猜测，希望作者可以看看，毕竟是crash级别的bug！
Thanks！

**Comment by AndrewSB** [comment]
Is this running on Android?

**Comment by sunshinejr** [comment]
Hey @T-mans, I believe you got the wrong repository, this one is for Swift 😆 [Here](https://github.com/tbruyelle/RxPermissions) is the Java version, please make an issue there 😉
